// File generated by Antigravity configuration.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2Q_i8Zp0zpQnC6tCR4KKDe0NOI1njeYI',
    appId: '1:453613002299:web:77ee318a42c82e917e061e',
    messagingSenderId: '453613002299',
    projectId: 'washify-7638b',
    authDomain: 'washify-7638b.firebaseapp.com',
    storageBucket: 'washify-7638b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2Q_i8Zp0zpQnC6tCR4KKDe0NOI1njeYI',
    appId: '1:453613002299:android:ea9920a66d03d3f27e061e',
    messagingSenderId: '453613002299',
    projectId: 'washify-7638b',
    storageBucket: 'washify-7638b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2Q_i8Zp0zpQnC6tCR4KKDe0NOI1njeYI',
    appId: '1:453613002299:ios:ea9920a66d03d3f27e061e',
    messagingSenderId: '453613002299',
    projectId: 'washify-7638b',
    storageBucket: 'washify-7638b.firebasestorage.app',
    iosBundleId: 'com.example.washify',
  );
}
